apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: release-healthcheck
resources:
  - namespace.yaml
  - postgres.yaml
  - auth-service-configmap.yaml
  - auth-service-code.yaml
  - auth-service-deployment.yaml
